[package]
name = "vrf_dalek"
version = "0.1.0"
authors = ["iquerejeta <querejeta.azurmendi@iohk.io>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# The implementation of version 3 of the VRF function (the one used in Cardano previous to Babbage) always unsets
# the sign bit in the elligator function. However, the exposure that curve25519-dalek offers, does not allow us to
# modify the elligator function. Therefore we rely on a fork that simply sets the bit. This fork should be only
# one commit ahead over the tag of version 3.2.0. And the sole change is the sign flip.
curve25519-dalek-fork = { package = "curve25519-dalek", git = "https://github.com/txpipe/curve25519-dalek", branch = "ietf03_vrf_compat_ell2" }
curve25519-dalek = { version = "3" }
rand_core = "0.5"
sha2 = "0.9"
blake3 = { version = "1.2.0", optional = true }
thiserror = "1"

[dev-dependencies]
rand_chacha = "0.2"
hex = "0.4.2"
criterion = "0.3.5"

[features]
batch_deterministic = ["blake3"]

[[bench]]
name = "vrf10"
harness = false
